export async function seed(knex) {
  await knex('jobs').del();

  await knex('jobs').insert([
    {
      id: '77777777-7777-4777-8777-777777777771',
      created_by: '22222222-2222-4222-8222-222222222222',
      title: 'Développeur Full Stack Vue.js / Node.js',
      description: 'Nous recherchons un profil capable de construire des interfaces performantes, des APIs robustes et d améliorer une plateforme de recrutement intelligente.',
      requirements: 'Expérience solide en JavaScript, Vue.js, Node.js, PostgreSQL et bonnes pratiques DevOps.',
      skills_required: JSON.stringify(['Vue.js', 'Node.js', 'PostgreSQL', 'REST API']),
      skills_preferred: JSON.stringify(['Docker', 'Redis', 'Tailwind CSS']),
      department: 'Engineering',
      location: 'Paris',
      country: 'France',
      remote_allowed: true,
      remote_type: 'hybrid',
      employment_type: 'full_time',
      experience_level: 'mid',
      salary_min: 45000,
      salary_max: 60000,
      currency: 'EUR',
      salary_period: 'yearly',
      status: 'open',
      is_featured: true,
      is_urgent: false,
      published_at: '2026-03-20T08:00:00.000Z',
      deadline_at: '2026-04-20T23:59:59.000Z',
      applications_count: 1,
      views_count: 126,
      reference_number: 'SR-JOB-2026-001',
      benefits: 'Mutuelle premium, budget formation, télétravail flexible.',
      company_description: 'SmartRecruit construit des outils de recrutement augmentés par la donnée et l IA.',
      company_size: '51-200',
      industry: 'HR Tech',
      screening_questions: JSON.stringify([
        'Quelle est votre expérience avec Vue.js ?',
        'Avez-vous déjà déployé une API Node.js en production ?',
      ]),
      metadata: JSON.stringify({
        hiring_manager: 'Sarah Mensah',
        seeded: true,
      }),
    },
    {
      id: '77777777-7777-4777-8777-777777777772',
      created_by: '33333333-3333-4333-8333-333333333333',
      title: 'Data Analyst Recrutement & Performance',
      description: 'Poste orienté analyse de données, reporting RH, suivi des funnels de candidatures et optimisation des conversions.',
      requirements: 'Maîtrise de SQL, outils BI, construction de dashboards et analyse business.',
      skills_required: JSON.stringify(['SQL', 'Power BI', 'Analytics']),
      skills_preferred: JSON.stringify(['Python', 'Machine Learning', 'A/B Testing']),
      department: 'Data',
      location: 'Lyon',
      country: 'France',
      remote_allowed: true,
      remote_type: 'full_remote',
      employment_type: 'full_time',
      experience_level: 'senior',
      salary_min: 50000,
      salary_max: 68000,
      currency: 'EUR',
      salary_period: 'yearly',
      status: 'open',
      is_featured: false,
      is_urgent: true,
      published_at: '2026-03-22T10:00:00.000Z',
      deadline_at: '2026-04-25T23:59:59.000Z',
      applications_count: 1,
      views_count: 89,
      reference_number: 'SR-JOB-2026-002',
      benefits: 'Prime variable, équipement premium, accompagnement carrière.',
      company_description: 'Entreprise spécialisée dans la data appliquée aux ressources humaines.',
      company_size: '11-50',
      industry: 'People Analytics',
      screening_questions: JSON.stringify([
        'Quel dashboard métier avez-vous construit récemment ?',
      ]),
      metadata: JSON.stringify({
        hiring_manager: 'Marc Traore',
        seeded: true,
      }),
    },
  ]);
}
